// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RajShoeApp.Model;

namespace RajShoeApp.Migrations
{
    [DbContext(typeof(ShoeModelContext))]
    partial class ShoeModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RajShoeApp.Model.ShoeModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<string>("Colour");

                    b.Property<string>("Name");

                    b.Property<float>("Price");

                    b.Property<string>("Size");

                    b.Property<float>("Weight");

                    b.Property<string>("category");

                    b.HasKey("Id");

                    b.ToTable("ShoeData");
                });
#pragma warning restore 612, 618
        }
    }
}
